# Generated by Django 5.2.4 on 2025-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1000)),
                ('lname', models.CharField(max_length=1000)),
                ('mobile', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
                ('on_site', models.CharField(default='بله', verbose_name=[('بله', 'yes'), ('خیر', 'no')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
