# Generated by Django 5.2.4 on 2025-07-25 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=11)),
                ('black_list', models.BooleanField(default=False)),
                ('black_list_reason', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='on_site',
            field=models.CharField(choices=[('بله', 'yes'), ('خیر', 'no')], default='بله', max_length=3),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('sell_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personnel')),
            ],
        ),
    ]
