# Generated by Django 5.2.4 on 2025-07-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_personnel_is_active_alter_personnel_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.work'),
            preserve_default=False,
        ),
    ]
