# Generated by Django
from django.db import migrations, models
import datetime

def create_default_data(apps, schema_editor):
    # مدل‌ها
    Work = apps.get_model('app', 'Work')
    Personnel = apps.get_model('app', 'Personnel')
    PersonnelCommission = apps.get_model('app', 'PersonnelCommission')
    Bank = apps.get_model('app', 'Bank')
    Customer = apps.get_model('app', 'Customer')
    PayType = apps.get_model('app', 'PayType')
    ReceiptType = apps.get_model('app', 'ReceiptType')
    PaymentMethod = apps.get_model('app', 'PaymentMethod')

    today = datetime.date.today()

    # 1. خدمت پیش فرض
    work, _ = Work.objects.get_or_create(work_name="کوتاهی مو")

    # 2. پرسنل پیش فرض
    personnel, _ = Personnel.objects.get_or_create(
        fname="پیش فرض",
        lname="",
        mobile="00000000000",
        defaults={'on_site': 'بله'}
    )

    # 3. کمیسیون پیش فرض پرسنل برای خدمت
    PersonnelCommission.objects.get_or_create(
        personnel=personnel,
        work=work,
        defaults={'percentage': 60, 'start_date': today, 'end_date': today.replace(year=today.year + 10)}
    )

    # 4. بانک پیش فرض
    Bank.objects.get_or_create(name="پاسارگاد")

    # 5. مشتری پیش فرض
    Customer.objects.get_or_create(
        fname="پیش فرض",
        lname="",
        mobile="00000000000"
    )

    # 6. PayType
    PayType.objects.get_or_create(name="هزینه", is_personnel=False)
    PayType.objects.get_or_create(name="پرسنل", is_personnel=True)

    # 7. ReceiptType
    ReceiptType.objects.get_or_create(name="سایر", is_customer=False)
    ReceiptType.objects.get_or_create(name="مشتری", is_customer=True)

    # 8. PaymentMethod
    PaymentMethod.objects.get_or_create(name="نقد", requires_bank=False)
    PaymentMethod.objects.get_or_create(name="حساب بانکی", requires_bank=True)


class Migration(migrations.Migration):

    dependencies = [
        # <- اینجا باید آخرین migration مدل‌ها قرار بگیره
        ('app', '0002_create_superuser'),
    ]

    operations = [
        migrations.RunPython(create_default_data),
    ]
