# Generated by Django 5.2.4 on 2025-07-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_work_sale_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sell_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='black_list_reason',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='comment',
            field=models.TextField(blank=True, default='2025-07-25 22:56:04+03:30'),
            preserve_default=False,
        ),
    ]
