# Generated by Django 5.2.4 on 2025-08-05 06:58

from django.db import migrations
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_sell_date_sale_date_and_more'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model
        User = get_user_model()
        if User.objects.exists():
            return
        
        superuser = User.objects.create_superuser(
            username="masoud",
            email="masoud.Hesaraki1985@gmail.com",
            password="1234",
            last_login=timezone.now()
        )

        superuser.save()


    operations = [
        migrations.RunPython(create_superuser)
    ]
