# Generated by Django 5.2.4 on 2025-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transactiontype_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='effect',
            field=models.SmallIntegerField(choices=[(1, 'افزایش موجودی'), (-1, 'کاهش موجودی')], default=1),
        ),
    ]
