# Generated by Django 5.2.4 on 2025-08-12 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_transaction_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_percentage',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='PersonnelCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personnel')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.work')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='app.personnel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
