# Generated by Django 5.2.4 on 2025-08-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sale_commission_amount_sale_commission_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.customer')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personnel')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.work')),
            ],
        ),
    ]
