# Generated by Django 5.2.4 on 2025-08-18 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_paytype_receipttype_pay_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.sale'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='app.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.personnel'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.work'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paytype'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='app.personnel'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.sale'),
        ),
        migrations.AlterField(
            model_name='personnelcommission',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.personnel'),
        ),
        migrations.AlterField(
            model_name='personnelcommission',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.work'),
        ),
        migrations.AlterField(
            model_name='personneluser',
            name='personnel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to='app.personnel'),
        ),
        migrations.AlterField(
            model_name='personneluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personnel_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts_made', to='app.customer'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.receipttype'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.personnel'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.work'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.transactiontype'),
        ),
    ]
