# Generated by Django 5.2.4 on 2025-08-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_receipt_sale_alter_appointment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sale'),
        ),
    ]
