# Generated by Django 5.2.4 on 2025-08-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_name_customer_fname_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sale_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.sale')),
            ],
        ),
    ]
