# Generated by Django 5.2.4 on 2025-08-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_saleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleimage',
            name='image_type',
            field=models.CharField(choices=[('before', 'قبل'), ('after', 'بعد')], default='after', max_length=10),
            preserve_default=False,
        ),
    ]
