# Generated by Django 5.2.4 on 2025-08-07 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0007_alter_sale_date_alter_work_work_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personnel')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.work')),
            ],
        ),
    ]
