"""
Django settings for medusa project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import pymysql  # ← اضافه شده برای جایگزینی mysqlclient
pymysql.install_as_MySQLdb()  # ← اضافه شده

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e$ocm#*6udtm&cci87lo8w2j&#34u$#ev%)rpm8ixkv_&g9j^o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # ← روی هاست production False باشه

ALLOWED_HOSTS = ["medusa-beauty.ir", "www.medusa-beauty.ir"]  # ← دامنه هاست

# THIRD_PARTY_APPS = [
#     "django-browser-reload",
#     "widget_tweaks",
# ]

INSTALLED_APPS = [
    'app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jalali_date',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'app.middleware.LoginRequiredMiddleware', 
]

ROOT_URLCONF = 'medusa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medusa.wsgi.application'

# ===================== DATABASE =====================
# استفاده از PyMySQL بجای mysqlclient برای هاست های shared
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'medusa_beauty',
        'USER': 'masoud',
        'PASSWORD': '44806238@q',  # ← پسورد روی سرور هاست
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# ===================== AUTH PASSWORD VALIDATION =====================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True
# USE_L10N = True
# USE_TZ = True

# ===================== STATIC & MEDIA =====================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# تنظیمات تاریخ جلالی
JALALI_DATE_FORMAT = "%Y/%m/%d _ %H:%M"

# ===================== LOGIN/LOGOUT =====================
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'   # بعد از ورود کجا بره
LOGOUT_REDIRECT_URL = 'login'

# ===================== LOGGING =====================
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     }
# }
